### ISSUE TITLE
How to understand the c hf vf in .txt

### ISSUE THREAD

**Issue by rRaphae1** [rfww/IDET#1]
The data of CMU seems to get in <Selecting change image for efficient change detection>, and I don't understand what the suffix c hf vf means. Could you please tell the means to help me run the code.

**Comment by rfww** [comment]
Yeah, of course. 
c:  random crop
hf: horizontal flip
vf: vertical flip
Please note that our random crop doesn't mean cropping the whole image randomly, it's cropping the changed object with a random size box. You can remove these augmented files or make your own dataset files. It's just an example.
If you have any using problems, please let me know.

**Comment by rfww** [comment]
> The data of CMU seems to get in , and I don't understand what the suffix c hf vf means. Could you please tell the means to help me run the code.

Yeah, of course.
c: random crop
hf: horizontal flip
vf: vertical flip
Please note that our random crop doesn't mean cropping the whole image randomly, it's cropping the changed object with a random size box. You can remove these augmented files or make your own dataset files. It's just an example.
If you have any using problems, please let me know.

**Comment by rRaphae1** [comment]
ok, I get it, thanks for your answering.
