### ISSUE TITLE
params

### ISSUE THREAD

**Issue by yuwanting828** [rfww/IDET#2]
Hello! Could you provide the number of params. (M) and FLOPS(G)? Thank you very much!

**Comment by rfww** [comment]
We have provided the details in the ablation study of our paper (https://arxiv.org/abs/2207.09240#).

**Comment by yuwanting828** [comment]
Thanks for your reply, I only found your GFLOPs values in the TABLE VII, so I was wondering if there was a params value reference, thanks!

**Comment by rfww** [comment]
Okay， I will evaluate the params later, or you can run the code to test it yourself. The GFLOPS may be different due to the types of GPU, while the parameters will be the same.

**Comment by rfww** [comment]
I don't have any free GPUs right now.  So please wait for a while.   ^.^

**Comment by yuwanting828** [comment]
OK! Thank you very much! Have a wonderful life!

**Comment by rfww** [comment]
Hey. The total number of parameters of IDET (T=2) is 119.1209M. I implemented the function for computing the number of parameters in train.py (print_model()). If you want to calculate the num of params of IDET with different iterations, please run it yourself. Thanks for concerning our work.
