### ISSUE TITLE
自制数据集问题

### ISSUE THREAD

**Issue by Onlyooo** [rfww/IDET#4]
请问作者大佬，我自制的数据集是按照CMU的格式制作的，为什么跑完网络之后，测试的结果图是纯黑色的呢？

**Comment by rfww** [comment]
应该是你的label不是二值图（0 or 1）, 可以检查下label

**Comment by Onlyooo** [comment]
谢谢大佬，我检查了一下确实不是，我修改之后再跑一下试试！
